#!/bin/bash


# env
if [ ! -f ./.env ]; then
    cp ./.env.example ./.env
fi

# install PHP deps
composer install

# install node deps
yarn

# configure craft
nanobox run ./scripts/project/nanobox-after-install

# git-flow
git flow init
